/* out.cpp 
   CREATED Mon Jun 20 01:21:58 2016

   GENERATED BY the sm4ceps C++ Generator VERSION 0.3 (c) Tomas Prerovsky <tomas.prerovsky@gmail.com>, ALL RIGHTS RESERVED. 
   Requires C++1y compatible compiler (use --std=c++11 for g++) 
   BASED ON cepS VERSION 1.1 (May 28 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/




#include "out.hpp"



void user_defined_init(){
}
 void globfuncs::S__action__OnA(){
  std::cout<<std::string{R"(A occured!
)"};
 }
extern "C" void init_plugin(IUserdefined_function_registry* smc){
smc->register_action("S","OnA", globfuncs::S__action__OnA);

}