/* LOG4KMW_STATES.HPP 
   CREATED Mon May 30 23:26:54 2016

   GENERATED BY logspec2cpp VERSION 0.6 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (May 28 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_STATES_HPP_INC
#define LOG4KMW_STATES_HPP_INC

#include "log4kmw_state.hpp"
#include "log4kmw_dynamic_bitset.hpp"
#include<string>
#include<thread>
#include<mutex>
#include<time.h>

namespace log4kmw_states{
 extern std::mutex global_lock;
 extern log4kmw::State<int> Current_event;
 extern log4kmw::State<log4kmw::Dynamic_bitset> Current_states;
 extern log4kmw::State<timespec> Timestamp;

 typedef log4kmw::State<int> Current_event_t;
 typedef log4kmw::State<log4kmw::Dynamic_bitset> Current_states_t;
 typedef log4kmw::State<timespec> Timestamp_t;

 void write_state_Current_event(Current_event_t const &);
 Current_event_t   read_state_Current_event(); 
 Current_event_t   read_state_Current_event_no_lock(); 
 void write_state_Current_states(Current_states_t const &);
 Current_states_t   read_state_Current_states(); 
 Current_states_t   read_state_Current_states_no_lock(); 
 void write_state_Timestamp(Timestamp_t const &);
 Timestamp_t   read_state_Timestamp(); 
 Timestamp_t   read_state_Timestamp_no_lock(); 
}

#endif
