/* LOG4KMW_EVENTS.HPP 
   CREATED Mon May 30 23:26:54 2016

   GENERATED BY logspec2cpp VERSION 0.6 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (May 28 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


/* LOG4KMW_EVENTS.CPP 
   CREATED Mon May 30 23:26:54 2016

   GENERATED BY logspec2cpp VERSION 0.6 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (May 28 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_EVENTS_HPP_INC
#define LOG4KMW_EVENTS_HPP_INC

#include "log4kmw_event.hpp"


namespace log4kmw_events{
 typedef log4kmw::Event<0> Step;
}

#endif
