/* LOG4KMW_LOGGERS.CPP 
   CREATED Mon May 30 23:26:54 2016

   GENERATED BY logspec2cpp VERSION 0.6 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (May 28 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/



#include "log4kmw_records.hpp"
#include "log4kmw_loggers.hpp"

 log4kmw_loggers::logger_Trace_t log4kmw_loggers::logger_Trace;
std::mutex log4kmw_loggers::logger_mutex_Trace;
 void log4kmw_loggers::log_event(log4kmw_events::Step const & ev, log4kmw_loggers::logger_Trace_t & log)
{
 if(!log.logger()) throw std::runtime_error("Logger 'Trace' invalid (not initialized?)");
 log4kmw_records::Trace rec;
 log4kmw_records::make_record_from_states(rec);
 {
  std::unique_lock<std::mutex> lock(log4kmw_loggers::logger_mutex_Trace);
  log.logger().append(rec.record());
 }
}

