#!/bin/bash
echo "=====> case_read_field_in_substruct:" && ceps case_read_field_in_substruct.ceps
echo "=====> case_read_non_existing_field_with_onerror:" && ceps case_read_non_existing_field_with_onerror.ceps
echo "=====> case_read_non_existing_field:" && ceps case_read_non_existing_field.ceps
echo "=====> case_read_existing_field:" && ceps case_read_existing_field.ceps
