#!/bin/bash
echo "=====> case_read_field_in_substruct:" && ceps case_read_field_in_substruct.ceps
echo "=====> case_read_non_existing_field_with_onerror:" && ceps case_read_non_existing_field_with_onerror.ceps
echo "=====> case_read_non_existing_field:" && ceps case_read_non_existing_field.ceps
echo "=====> case_read_existing_field:" && ceps case_read_existing_field.ceps
echo "=====> case_read_fields_in_wrong_order:" && ceps case_read_fields_in_wrong_order.ceps
echo "=====> case_read_two_fields_in_substruct:" && ceps  case_read_two_fields_in_substruct.ceps
echo "=====> case_using_allmodifier:" && ceps case_using_allmodifier.ceps
echo "=====> case_write_empty_message:" && ceps case_write_empty_message.ceps
echo "=====>  case_write_read_empty_message: "&& ceps case_write_read_empty_message.ceps
echo "=====>  case_write_read_empty_message2: " && ceps case_write_read_empty_message2.ceps