/* out_frames.hpp 
   CREATED Fri Jun 24 16:52:53 2016

   GENERATED BY the sm4ceps C++ Generator VERSION 0.50 (c) Tomas Prerovsky <tomas.prerovsky@gmail.com>, ALL RIGHTS RESERVED. 
   Requires C++1y compatible compiler (use --std=c++1y for g++) 
   BASED ON cepS VERSION 1.1 (Jun 24 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files (relative paths):
      /home/cb/subversion/TRGS/statemachines/control/base_defs.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_disable.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_enable.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_brake_release.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_brake_apply.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_move.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_reset_fault_antrieb.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_to_indexposition.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_to_target_position.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_move_left_down.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/x_drive_move_right_down.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_disable.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_enable.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_brake_release.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_brake_apply.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_move.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_reset_fault_antrieb.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_to_arbeitsposition.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_to_indexposition.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_to_target_position.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_move_front_down.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/y_drive_move_rear_down.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_disable.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_enable.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_brake_release.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_brake_apply.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_move.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_reset_fault_antrieb.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_to_index_position.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_to_lashing_position.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_to_target_position.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_move_down.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/z_drive_move_up.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/ctrl.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/dispatch.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_lashing_lock.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_lashing_unlock.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_lock_preconditioning.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_to_hinge_down.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_to_level_out.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_to_parking_position.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/antenna_to_raise.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/dust_discharge_to_do.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_close.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_lock.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_open.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_precondition.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_to_close.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_to_open.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/flap_unlock.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/platform_extend.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/platform_extend_fto_and_alu.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/platform_retract.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/platform_retract_ftc_and_all.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/platform_retract_preconditioning.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_extend.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_lock.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_preconditioning.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_retract.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_to_extend.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_to_retract.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/stilts_unlock.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/system_extend.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-programs/system_retract.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/antenna_alignment.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/antenna_lashing.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/drives_state.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/dust_discharge.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/extbg_progress_indicator.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/extbg_error_evaluator.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/flap.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/flap_lock_one.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/flap_lock_two.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/funktionsueberwachung.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/io_module_controler.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/ivenet_state.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/pneumatic_cylinder_pressure.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/stilt_left.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/stilt_right.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/stilts_vk_left.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/stilts_vk_right.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/user_buttons.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/warning_mast_operations.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/x_drive_fault_state.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/y_drive_fault_state.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-state/z_drive_fault_state.ceps
      /home/cb/subversion/TRGS/statemachines/control/sm-dingo/talin.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_fue.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_drives.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_io_modul.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_si_modul.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_extbg.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_ivenet.ceps
      /home/cb/subversion/TRGS/statemachines/network/messages/messages_sae.ceps
      /home/cb/subversion/TRGS/statemachines/network/bag/rx-bag.ceps
      /home/cb/subversion/TRGS/statemachines/network/bag/rx-bag-sae.ceps
      /home/cb/subversion/TRGS/statemachines/network/bag/tx-bag-ivenet.ceps
      /home/cb/subversion/TRGS/statemachines/network/bag/tx-bag.ceps
      /home/cb/subversion/TRGS/statemachines/network/bag/channels-bag-vcan.ceps
      /home/cb/subversion/TRGS/statemachines/network/gencpp.ceps

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/


namespace raw_frm_dcls{
 struct frame_heartbeat_x_drive_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_x_drive_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_y_drive_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_y_drive_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_z_drive_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_z_drive_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_io_module_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_io_module_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_si_module_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_si_module_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_usv_1_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_usv_1_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_usv_2_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_usv_2_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_extbg_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_extbg_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_bag_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_bag_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_heartbeat_generic_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_heartbeat_generic_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_set_operational_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));
 struct frame_set_operational_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));

 struct frame_drive_request_x_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  unsigned char pos_7:3;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
 }__attribute__ ((__packed__));
 struct frame_drive_request_x_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  unsigned char pos_7:3;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
 }__attribute__ ((__packed__));

 struct frame_drive_request_y_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  unsigned char pos_7:3;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
 }__attribute__ ((__packed__));
 struct frame_drive_request_y_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  unsigned char pos_7:3;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
 }__attribute__ ((__packed__));

 struct frame_drive_request_z_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  unsigned char pos_7:3;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
 }__attribute__ ((__packed__));
 struct frame_drive_request_z_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  unsigned char pos_7:3;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
 }__attribute__ ((__packed__));

 struct frame_x_drive_response_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
 }__attribute__ ((__packed__));
 struct frame_x_drive_response_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
 }__attribute__ ((__packed__));

 struct frame_y_drive_response_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
 }__attribute__ ((__packed__));
 struct frame_y_drive_response_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
 }__attribute__ ((__packed__));

 struct frame_z_drive_response_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
 }__attribute__ ((__packed__));
 struct frame_z_drive_response_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  short pos_5:12;
  short pos_6:12;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
 }__attribute__ ((__packed__));

 struct frame_x_drive_emcy_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  unsigned int pos_22:24;
 }__attribute__ ((__packed__));
 struct frame_x_drive_emcy_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  unsigned int pos_22:24;
 }__attribute__ ((__packed__));

 struct frame_y_drive_emcy_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  unsigned int pos_22:24;
 }__attribute__ ((__packed__));
 struct frame_y_drive_emcy_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  unsigned int pos_22:24;
 }__attribute__ ((__packed__));

 struct frame_z_drive_emcy_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  unsigned int pos_22:24;
 }__attribute__ ((__packed__));
 struct frame_z_drive_emcy_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  unsigned int pos_22:24;
 }__attribute__ ((__packed__));

 struct io_modul_betriebsart_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct io_modul_betriebsart_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct io_modul_ansteuerung_ausgaenge_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));
 struct io_modul_ansteuerung_ausgaenge_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));

 struct io_modul_force_pdo_transmit_hv_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct io_modul_force_pdo_transmit_hv_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct io_modul_geraetestatus_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct io_modul_geraetestatus_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct io_modul_zustand_heckverteiler_1_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
  char pos_47:1;
  char pos_48:1;
  char pos_49:1;
  char pos_50:1;
  char pos_51:1;
  char pos_52:1;
  char pos_53:1;
  char pos_54:1;
  char pos_55:1;
  char pos_56:1;
  char pos_57:1;
  char pos_58:1;
  char pos_59:1;
  char pos_60:1;
  char pos_61:1;
  char pos_62:1;
  char pos_63:1;
  char pos_64:1;
  char pos_65:1;
  char pos_66:1;
  char pos_67:1;
 }__attribute__ ((__packed__));
 struct io_modul_zustand_heckverteiler_1_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
  char pos_47:1;
  char pos_48:1;
  char pos_49:1;
  char pos_50:1;
  char pos_51:1;
  char pos_52:1;
  char pos_53:1;
  char pos_54:1;
  char pos_55:1;
  char pos_56:1;
  char pos_57:1;
  char pos_58:1;
  char pos_59:1;
  char pos_60:1;
  char pos_61:1;
  char pos_62:1;
  char pos_63:1;
  char pos_64:1;
  char pos_65:1;
  char pos_66:1;
  char pos_67:1;
 }__attribute__ ((__packed__));

 struct io_modul_zustand_heckverteiler_2_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));
 struct io_modul_zustand_heckverteiler_2_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));

 struct io_modul_talin_daten_1_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  int pos_5:32;
 }__attribute__ ((__packed__));
 struct io_modul_talin_daten_1_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  int pos_5:32;
 }__attribute__ ((__packed__));

 struct io_modul_talin_daten_2_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
 }__attribute__ ((__packed__));
 struct io_modul_talin_daten_2_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  int pos_4:32;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
 }__attribute__ ((__packed__));

 struct io_modul_fahrzeugwinkel_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  short pos_5:16;
  short pos_6:16;
 }__attribute__ ((__packed__));
 struct io_modul_fahrzeugwinkel_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  short pos_5:16;
  short pos_6:16;
 }__attribute__ ((__packed__));

 struct io_modul_luftdruck_pneumatiktank_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct io_modul_luftdruck_pneumatiktank_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct io_modul_software_version_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
 }__attribute__ ((__packed__));
 struct io_modul_software_version_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
 }__attribute__ ((__packed__));

 struct io_modul_fehler_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));
 struct io_modul_fehler_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));

 struct io_modul_rueckmeldung_ios_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));
 struct io_modul_rueckmeldung_ios_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
 }__attribute__ ((__packed__));

 struct io_modul_sensordaten_windmesser_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:8;
  char pos_5:8;
 }__attribute__ ((__packed__));
 struct io_modul_sensordaten_windmesser_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:8;
  char pos_5:8;
 }__attribute__ ((__packed__));

 struct si_modul_betriebsart_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct si_modul_betriebsart_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct si_modul_ansteuerung_ausgaenge_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
 }__attribute__ ((__packed__));
 struct si_modul_ansteuerung_ausgaenge_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
 }__attribute__ ((__packed__));

 struct si_modul_force_pdo_transmit_hv_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct si_modul_force_pdo_transmit_hv_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct si_modul_geraetestatus_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct si_modul_geraetestatus_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct si_modul_digitale_eingaenge_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
 }__attribute__ ((__packed__));
 struct si_modul_digitale_eingaenge_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_1_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_1_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_2_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_2_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_3_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_3_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_4_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_4_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_5_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_5_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_6_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_6_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_7_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_7_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct si_modul_analoge_eingaenge_8_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));
 struct si_modul_analoge_eingaenge_8_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
 }__attribute__ ((__packed__));

 struct frame_extbg_messwerte_navigation_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
  unsigned short pos_7:16;
 }__attribute__ ((__packed__));
 struct frame_extbg_messwerte_navigation_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned short pos_6:16;
  unsigned short pos_7:16;
 }__attribute__ ((__packed__));

 struct frame_extbg_zustand_plattform_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  unsigned short pos_21:16;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
 }__attribute__ ((__packed__));
 struct frame_extbg_zustand_plattform_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  unsigned short pos_21:16;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
 }__attribute__ ((__packed__));

 struct frame_betriebsstunden_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned int pos_4:32;
 }__attribute__ ((__packed__));
 struct frame_betriebsstunden_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned int pos_4:32;
 }__attribute__ ((__packed__));

 struct frame_extbg_zustand_komponenten_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
 }__attribute__ ((__packed__));
 struct frame_extbg_zustand_komponenten_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
 }__attribute__ ((__packed__));

 struct frame_extbg_motordaten_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned short pos_7:16;
 }__attribute__ ((__packed__));
 struct frame_extbg_motordaten_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned short pos_7:16;
 }__attribute__ ((__packed__));

 struct frame_extbg_zustand_ruestsatz_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_zustand_ruestsatz_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned short pos_5:16;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
 }__attribute__ ((__packed__));

 struct frame_bag_software_version_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));
 struct frame_bag_software_version_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));

 struct frame_bag_betriebsmodus_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_bag_betriebsmodus_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_bag_piktogramme_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_bag_piktogramme_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_fortschritt_automatikbetrieb_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
  unsigned char pos_8:8;
  unsigned char pos_9:8;
  unsigned char pos_10:8;
  unsigned char pos_11:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_fortschritt_automatikbetrieb_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
  unsigned char pos_8:8;
  unsigned char pos_9:8;
  unsigned char pos_10:8;
  unsigned char pos_11:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_x_drive_sollwerte_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_x_drive_sollwerte_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_y_drive_sollwerte_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_y_drive_sollwerte_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_z_drive_sollwerte_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_z_drive_sollwerte_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_force_bag_pdo_transmit_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_force_bag_pdo_transmit_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_betriebsart_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));
 struct frame_extbg_betriebsart_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
 }__attribute__ ((__packed__));

 struct frame_extbg_taster_betaetigung_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
  char pos_47:1;
  char pos_48:1;
  char pos_49:1;
  char pos_50:1;
  char pos_51:1;
 }__attribute__ ((__packed__));
 struct frame_extbg_taster_betaetigung_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
  char pos_47:1;
  char pos_48:1;
  char pos_49:1;
  char pos_50:1;
  char pos_51:1;
 }__attribute__ ((__packed__));

 struct frame_extbg_taster_manuell_betaetigung_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
  char pos_47:1;
  char pos_48:1;
  char pos_49:1;
  char pos_50:1;
  char pos_51:1;
 }__attribute__ ((__packed__));
 struct frame_extbg_taster_manuell_betaetigung_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  char pos_4:1;
  char pos_5:1;
  char pos_6:1;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
  char pos_39:1;
  char pos_40:1;
  char pos_41:1;
  char pos_42:1;
  char pos_43:1;
  char pos_44:1;
  char pos_45:1;
  char pos_46:1;
  char pos_47:1;
  char pos_48:1;
  char pos_49:1;
  char pos_50:1;
  char pos_51:1;
 }__attribute__ ((__packed__));

 struct frame_GPM_13_in{
  unsigned int pos_1:29;
  unsigned char pos_2:3;
  unsigned char pos_3:8;
  unsigned char pos_4:4;
  unsigned char pos_5:2;
  unsigned char pos_6:2;
  unsigned char pos_7:8;
  unsigned char pos_8:8;
  unsigned short pos_9:16;
  unsigned char pos_10:8;
  unsigned short pos_11:16;
 }__attribute__ ((__packed__));
 struct frame_GPM_13_out{
  unsigned int pos_1:29;
  unsigned char pos_2:3;
  unsigned char pos_3:8;
  unsigned char pos_4:4;
  unsigned char pos_5:2;
  unsigned char pos_6:2;
  unsigned char pos_7:8;
  unsigned char pos_8:8;
  unsigned short pos_9:16;
  unsigned char pos_10:8;
  unsigned short pos_11:16;
 }__attribute__ ((__packed__));

 struct frame_GPM_14_in{
  unsigned int pos_1:29;
  unsigned char pos_2:3;
  unsigned char pos_3:8;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned short pos_6:16;
  unsigned short pos_7:16;
  unsigned char pos_8:8;
  unsigned char pos_9:8;
 }__attribute__ ((__packed__));
 struct frame_GPM_14_out{
  unsigned int pos_1:29;
  unsigned char pos_2:3;
  unsigned char pos_3:8;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned short pos_6:16;
  unsigned short pos_7:16;
  unsigned char pos_8:8;
  unsigned char pos_9:8;
 }__attribute__ ((__packed__));

 struct frame_GPM_16_in{
  unsigned int pos_1:29;
  unsigned char pos_2:3;
  unsigned char pos_3:8;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
  unsigned short pos_8:16;
  unsigned char pos_9:8;
 }__attribute__ ((__packed__));
 struct frame_GPM_16_out{
  unsigned int pos_1:29;
  unsigned char pos_2:3;
  unsigned char pos_3:8;
  unsigned short pos_4:16;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  unsigned char pos_7:8;
  unsigned short pos_8:16;
  unsigned char pos_9:8;
 }__attribute__ ((__packed__));

}
