/* out_frames.cpp 
   CREATED Fri Jun 24 17:33:01 2016

   GENERATED BY the sm4ceps C++ Generator VERSION 0.50 (c) Tomas Prerovsky <tomas.prerovsky@gmail.com>, ALL RIGHTS RESERVED. 
   Requires C++1y compatible compiler (use --std=c++1y for g++) 
   BASED ON cepS VERSION 1.1 (Jun  1 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files (relative paths):
      raw_frame_ex_1_basedefs.ceps
      raw_frame_ex_1_receiver.ceps

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/


