/* out_frames.hpp 
   CREATED Fri Jun 24 17:33:01 2016

   GENERATED BY the sm4ceps C++ Generator VERSION 0.50 (c) Tomas Prerovsky <tomas.prerovsky@gmail.com>, ALL RIGHTS RESERVED. 
   Requires C++1y compatible compiler (use --std=c++1y for g++) 
   BASED ON cepS VERSION 1.1 (Jun  1 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files (relative paths):
      raw_frame_ex_1_basedefs.ceps
      raw_frame_ex_1_receiver.ceps

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/


namespace raw_frm_dcls{
 struct frame_zustand_komponenten_in{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
 }__attribute__ ((__packed__));
 struct frame_zustand_komponenten_out{
  unsigned short pos_1:11;
  char pos_2:1;
  unsigned char pos_3:4;
  unsigned char pos_4:8;
  unsigned char pos_5:8;
  unsigned char pos_6:8;
  char pos_7:1;
  char pos_8:1;
  char pos_9:1;
  char pos_10:1;
  char pos_11:1;
  char pos_12:1;
  char pos_13:1;
  char pos_14:1;
  char pos_15:1;
  char pos_16:1;
  char pos_17:1;
  char pos_18:1;
  char pos_19:1;
  char pos_20:1;
  char pos_21:1;
  char pos_22:1;
  char pos_23:1;
  char pos_24:1;
  char pos_25:1;
  char pos_26:1;
  char pos_27:1;
  char pos_28:1;
  char pos_29:1;
  char pos_30:1;
  char pos_31:1;
  char pos_32:1;
  char pos_33:1;
  char pos_34:1;
  char pos_35:1;
  char pos_36:1;
  char pos_37:1;
  char pos_38:1;
 }__attribute__ ((__packed__));

}
