/* out.hpp 
   CREATED Fri Mar 17 05:02:44 2017

   GENERATED BY THE sm4ceps C++ GENERATOR VERSION 0.90.
   BASED ON cepS (c) 2017 Tomas Prerovsky <tomas.prerovsky@gmail.com> VERSION 1.1 (Mar 10 2017) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files:
      prelude.ceps
      can3.xml

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/



#ifndef INC_SM4CEPS_GEN_OUT_HPP
#define INC_SM4CEPS_GEN_OUT_HPP
#include <iostream>
#include <string>
#include <algorithm>
#include <map>
#include <vector>
#include <cstdlib>
#include <cstring>
#include <sstream>
#include "core/include/state_machine_simulation_core_reg_fun.hpp"
#include "core/include/state_machine_simulation_core_plugin_interface.hpp"
#include "user_defined.hpp"
#include"out_frames.hpp"

 static Ism4ceps_plugin_interface* smcore_interface; 

namespace systemstates{


 using sm4ceps_plugin_int::Variant;
 using sm4ceps_plugin_int::ev;
 using sm4ceps_plugin_int::id;

 template<typename T> class State{
   T v_;
   bool changed_ = false;
 public:
   State() = default; 
   State(T const & v) { v_ = v;}
   State& operator = (State const & rhs){
     changed_ = v_ != rhs.v_;
     v_ = rhs.v_;
     return *this;
   }
   State& operator = (T const & rhs){
     changed_ = v_ != rhs;
     v_ = rhs;
     return *this;
   }
   bool changed() {auto t = changed_;changed_=false;return t;}
   void set_changed(bool t){changed_=t;}
   T& value() {return v_;}
   T value() const {return v_;} 
  };

 std::ostream& operator << (std::ostream& o, State<int> & v);
 std::ostream& operator << (std::ostream& o, State<double> & v); 
 State<int>& set_value(State<int>& lhs, Variant const & rhs);
 State<int>& set_value(State<int>& lhs, int rhs);
 State<double>& set_value(State<double>& lhs, double rhs);
 State<double>& set_value(State<double>& lhs, Variant const & rhs);
 State<std::string>& set_value(State<std::string>& lhs, std::string rhs);

extern State<double> rpm;
extern State<double> rpm_speed_src;
extern State<double> speed;

struct Engine_RPM_in_ctxt_t : public sm4ceps_plugin_int::Framecontext {
 decltype(systemstates::rpm) rpm_;
 decltype(systemstates::rpm_speed_src) rpm_speed_src_;
 decltype(systemstates::speed) speed_;
 void update_sysstates();
 void read_chunk(void*,size_t);
 bool match_chunk(void*,size_t);
 void init();
 Framecontext* clone();
 virtual ~Engine_RPM_in_ctxt_t();
};
extern Engine_RPM_in_ctxt_t Engine_RPM_in_ctxt;

}
namespace guards{

 using Guard = bool(*)();
 using Guard_impl = bool ();




}
namespace globfuncs{

 extern bool in_state(std::initializer_list<sm4ceps_plugin_int::id>);
 extern void start_timer(double,sm4ceps_plugin_int::ev);
 extern void start_timer(double,sm4ceps_plugin_int::ev,sm4ceps_plugin_int::id);
 extern void start_periodic_timer(double,sm4ceps_plugin_int::ev);
 extern void start_periodic_timer(double,sm4ceps_plugin_int::ev,sm4ceps_plugin_int::id);
 extern void stop_timer(sm4ceps_plugin_int::id);
 void start_periodic_timer(double t,sm4ceps_plugin_int::Variant (*fp)(),sm4ceps_plugin_int::id id_);
 void start_periodic_timer(double t,sm4ceps_plugin_int::Variant (*fp)());
 size_t argc();
 sm4ceps_plugin_int::Variant argv(size_t);
 extern bool send(systemstates::id,systemstates::id);


}
std::ostream& operator << (std::ostream& o, systemstates::Variant const & v);
raw_frm_dcls::Engine_RPM_out create_frame_Engine_RPM();
extern void user_defined_init();
#endif
