/* out_frames.hpp 
   CREATED Fri Mar 10 15:25:14 2017

   GENERATED BY THE sm4ceps C++ GENERATOR VERSION 0.80 (c) 2016 Tomas Prerovsky <tomas.prerovsky@gmail.com>, ALL RIGHTS RESERVED. 
   BASED ON cepS VERSION 1.1 (Mar 10 2017) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files:
      prelude.ceps
      can3.xml
      some_other_stuff.ceps

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/


namespace raw_frm_dcls{

}
