/* out_frames.cpp 
   CREATED Tue Mar 14 12:13:00 2017

   GENERATED BY THE sm4ceps C++ GENERATOR VERSION 0.90.
   BASED ON cepS (c) 2017 Tomas Prerovsky <tomas.prerovsky@gmail.com> VERSION 1.1 (Mar 10 2017) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files:
      prelude.ceps
      can3.xml

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/


