" Vim syntax file for the ceps language.
" GENERATED by tools/editor-support/generate.py -- do not edit by hand.
" Regenerate with: python3 tools/editor-support/generate.py

if exists("b:current_syntax")
  finish
endif

syn case match

" --- comments and strings -------------------------------------------------
syn keyword cepsTodo contained TODO FIXME XXX NOTE
syn match   cepsComment "//.*$" contains=cepsTodo
syn region  cepsComment start="/\*" end="\*/" contains=cepsTodo
syn match   cepsEscape  contained "\\."
syn region  cepsString  start=+"+ skip=+\\.+ end=+"+ contains=cepsEscape

" --- numbers --------------------------------------------------------------
syn match cepsNumber "\<\d\+\>"
syn match cepsFloat  "\<\d\+\.\d*\([eE][-+]\=\d\+\)\="

" --- keywords -------------------------------------------------------------
syn keyword cepsKeyword else for fun if kind label let macro
syn keyword cepsKeyword raw_map return static_for struct template val

" --- names that are really SI units ---------------------------------------
" DEFECTS.md D17: these fourteen names silently resolve to a unit rather than
" to whatever you meant, with exit code 0 and no diagnostic. They are linked to
" Todo rather than to a quiet group on purpose -- being hard to overlook is the
" entire point of highlighting them.
syn keyword cepsSIUnit ampere candela cd celsius kelvin kg kilogram m
syn keyword cepsSIUnit meter metre mol mole s second

" --- Oblectamenta ---------------------------------------------------------
syn keyword cepsOpcode adddbl addi32 addi64 andi32 andi64 andni32
syn keyword cepsOpcode andni64 assert_deserialized_protobufish_message_equals_str assert_empty_cs asserteqi32 assertf64 asserti32
syn keyword cepsOpcode asserti64 assertsz atandbl beq beqi64 beqi8
syn keyword cepsOpcode bgteq bgteqzeroi32 blt blteq blteqzeroi32 bltzeroi32
syn keyword cepsOpcode bneqi64 bneqi8 bnzerodbl bnzeroi32 bnzeroi64 bnzeroi8
syn keyword cepsOpcode buc bzerodbl bzeroi32 bzeroi64 bzeroi8 call
syn keyword cepsOpcode cosdbl cpysi32 dbg_deserialize_protobufish_to_json dbg_print_cs_and_regs dbg_print_data dbg_print_stack
syn keyword cepsOpcode dbg_print_topf64 dbg_print_topi32 dbg_print_topi64 dbg_println dbg_printlni32 dbg_printsz
syn keyword cepsOpcode discardtopi32 discardtopi64 divdbl divi32 divi64 duptopi128
syn keyword cepsOpcode duptopi192 duptopi32 duptopi64 duptopi8 eqdbl eqi32
syn keyword cepsOpcode eqi64 expdbl gtdbl gteqdbl gteqi32 gteqi64
syn keyword cepsOpcode gti32 gti64 halt lddbl ldi32 ldi64
syn keyword cepsOpcode ldi8 ldptr ldsdbl ldsi32 ldsi64 ldsi8
syn keyword cepsOpcode lea lea_absolute ltdbl lteqdbl lteqi32 lteqi64
syn keyword cepsOpcode lti32 lti64 msg muldbl muli32 muli64
syn keyword cepsOpcode negdbl negi32 negi64 noop noti32 noti64
syn keyword cepsOpcode ori32 ori64 popi32 popi64 pushi32 pushi64
syn keyword cepsOpcode remi32 remi64 ret setframe shli32 shli64
syn keyword cepsOpcode shri32 shri64 sindbl sri64 stdbl sti32
syn keyword cepsOpcode sti64 sti8 stptr stsdbl stsi32 stsi64
syn keyword cepsOpcode stsi8 subdbl subi32 subi64 swp swp128b8
syn keyword cepsOpcode swp128i64 swp192i64 swp72i64 swp80i64 swp96i64 swpi160i64
syn keyword cepsOpcode swpi16i128 swpi16i64 swpi192i32 swpi32i64 swpi64 swpi64b128
syn keyword cepsOpcode swpi64b72 swpi64i192 swpi8i128 swpi8i64 tandbl tanhdbl
syn keyword cepsOpcode ui32toui64 ui8toui32 ui8toui64 wrsi32 xori32 xori64
syn keyword cepsRegister ARG0 ARG1 ARG2 ARG3 ARG4 ARG5 FP R0
syn keyword cepsRegister R1 R10 R11 R12 R13 R14 R15 R2
syn keyword cepsRegister R3 R4 R5 R6 R7 R8 R9 RES
syn keyword cepsRegister SP addr reg

" --- structure ------------------------------------------------------------
" Order matters here: when two matches start at the same position vim gives
" priority to the one defined last, so the specific rules follow the general.
syn match cepsStructHead "\<[A-Za-z_]\w*\ze\s*{"
syn match cepsSMKeyword "\<\%(oblectamenta\|Simulation\|transition\|on_enter\|Actions\|on_exit\|Events\|Guards\|Thread\|global\|states\|Start\|data\|text\|asm\|msg\|x64\|sm\|t\)\>\ze\s*{"

syn match cepsKindName "\%(\<kind\s\+\)\@<=[A-Za-z_]\w*"

" A declaration, `Kind a, b, c;`. This has to be a container rather than one
" match: a name that is really a unit must keep its own group, which it would
" not if the whole declaration were a single match.
syn match cepsDecl "\<[A-Z]\w*\s\+[A-Za-z_]\w*\%(\s*,\s*[A-Za-z_]\w*\)*\s*;"
      \ contains=cepsSIUnit,cepsDeclName,cepsDeclKind
syn match cepsDeclName contained "\<[A-Za-z_]\w*\>"
syn match cepsDeclKind contained "\<[A-Z]\w*\%(\s\+[A-Za-z_]\)\@="

" --- operators ------------------------------------------------------------
syn match cepsOperator "<=\|>=\|==\|!=\|->\|<-\|\.\.\|[-+*/^~=<>|&!.:#]"

" --- linkage --------------------------------------------------------------
hi def link cepsComment    Comment
hi def link cepsTodo       Todo
hi def link cepsString     String
hi def link cepsEscape     SpecialChar
hi def link cepsNumber     Number
hi def link cepsFloat      Float
hi def link cepsKeyword    Keyword
hi def link cepsSIUnit     Todo
hi def link cepsOpcode     Function
hi def link cepsRegister   Constant
hi def link cepsSMKeyword  Structure
hi def link cepsKindName   Type
hi def link cepsDeclKind   Type
hi def link cepsDeclName   Identifier
hi def link cepsStructHead Function
hi def link cepsOperator   Operator

let b:current_syntax = "ceps"
