/* out.cpp 
   CREATED Tue Jul  5 23:21:50 2016

   GENERATED BY the sm4ceps C++ Generator VERSION 0.50 (c) Tomas Prerovsky <tomas.prerovsky@gmail.com>, ALL RIGHTS RESERVED. 
   Requires C++1y compatible compiler (use --std=c++1y for g++) 
   BASED ON cepS VERSION 1.1 (May 28 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 

   Input files (relative paths):
      substatemachines_a.ceps

   THIS IS A GENERATED FILE.

   *** DO NOT MODIFY. ***
*/




#include "out.hpp"

void init_frame_ctxts();


void user_defined_init(){
 init_frame_ctxts();
}


 void init_frame_ctxts(){
 }
 void globfuncs::S1__action__on_enter(){
  std::cout<<std::string{R"(S1::on_enter
)"};
 }
 void globfuncs::S1__action__on_exit(){
  std::cout<<std::string{R"(S1::on_exit
)"};
 }
 void globfuncs::S1__S1a__action__on_enter(){
  std::cout<<std::string{R"(S1::S1a::on_enter
)"};
 }
 void globfuncs::S1__S1a__action__on_exit(){
  std::cout<<std::string{R"(S1::S1a::on_exit
)"};
 }
 void globfuncs::S1__S1a__S1aa__action__on_enter(){
  std::cout<<std::string{R"(S1::S1a::S1aa::on_enter
)"};
 }
 void globfuncs::S1__S1a__S1aa__action__on_exit(){
  std::cout<<std::string{R"(S1::S1a::S1aa::on_exit
)"};
 }
 void globfuncs::S1__S1a__S1ab__action__on_enter(){
  std::cout<<std::string{R"(S1::S1a::S1ab::on_enter
)"};
 }
 void globfuncs::S1__S1a__S1ab__action__on_exit(){
  std::cout<<std::string{R"(S1::S1a::S1ab::on_exit
)"};
 }
 void globfuncs::S1__S1a__S1ac__action__on_enter(){
  std::cout<<std::string{R"(S1::S1a::S1ac::on_enter
)"};
 }
 void globfuncs::S1__S1a__S1ac__action__on_exit(){
  std::cout<<std::string{R"(S1::S1a::S1ac::on_exit
)"};
 }


extern "C" void init_plugin(IUserdefined_function_registry* smc){
smcore_interface = smc->get_plugin_interface();
smc->register_global_init(user_defined_init);
smc->register_action("S1","on_enter", globfuncs::S1__action__on_enter);
smc->register_action("S1","on_exit", globfuncs::S1__action__on_exit);
smc->register_action("S1.S1a","on_enter", globfuncs::S1__S1a__action__on_enter);
smc->register_action("S1.S1a","on_exit", globfuncs::S1__S1a__action__on_exit);
smc->register_action("S1.S1a.S1aa","on_enter", globfuncs::S1__S1a__S1aa__action__on_enter);
smc->register_action("S1.S1a.S1aa","on_exit", globfuncs::S1__S1a__S1aa__action__on_exit);
smc->register_action("S1.S1a.S1ab","on_enter", globfuncs::S1__S1a__S1ab__action__on_enter);
smc->register_action("S1.S1a.S1ab","on_exit", globfuncs::S1__S1a__S1ab__action__on_exit);
smc->register_action("S1.S1a.S1ac","on_enter", globfuncs::S1__S1a__S1ac__action__on_enter);
smc->register_action("S1.S1a.S1ac","on_exit", globfuncs::S1__S1a__S1ac__action__on_exit);
}

std::ostream& operator << (std::ostream& o, systemstates::Variant const & v)
{
 if (v.what_ == systemstates::Variant::Int)
  o << v.iv_;
 else if (v.what_ == systemstates::Variant::Double)
  o << std::to_string(v.dv_);
 else if (v.what_ == systemstates::Variant::String)
  o << v.sv_;
 else
  o << "(Undefined)";
 return o;
}

size_t globfuncs::argc(){
 return smcore_interface->argc();
}sm4ceps_plugin_int::Variant globfuncs::argv(size_t j){
 return smcore_interface->argv(j);
}
void globfuncs::start_timer(double t,sm4ceps_plugin_int::ev ev_){ smcore_interface->start_timer(t,ev_); }
void globfuncs::start_timer(double t,sm4ceps_plugin_int::ev ev_,sm4ceps_plugin_int::id id_){smcore_interface->start_timer(t,ev_,id_);}
void globfuncs::start_periodic_timer(double t ,sm4ceps_plugin_int::ev ev_){smcore_interface->start_periodic_timer(t,ev_);}
void globfuncs::start_periodic_timer(double t,sm4ceps_plugin_int::ev ev_,sm4ceps_plugin_int::id id_){smcore_interface->start_periodic_timer(t,ev_,id_);}
void globfuncs::start_periodic_timer(double t,sm4ceps_plugin_int::Variant (*fp)(),sm4ceps_plugin_int::id id_){smcore_interface->start_periodic_timer(t,fp,id_);}
void globfuncs::start_periodic_timer(double t,sm4ceps_plugin_int::Variant (*fp)()){smcore_interface->start_periodic_timer(t,fp);}
void globfuncs::stop_timer(sm4ceps_plugin_int::id id_){smcore_interface->stop_timer(id_);}
bool globfuncs::in_state(std::initializer_list<sm4ceps_plugin_int::id> state_ids){return smcore_interface->in_state(state_ids);}
