;;; ceps-mode.el --- Major mode for the ceps language -*- lexical-binding: t; -*-

;; GENERATED by tools/editor-support/generate.py -- do not edit by hand.
;; Regenerate with: python3 tools/editor-support/generate.py

;;; Commentary:

;; Syntax highlighting for .ceps files, covering the language proper and the
;; Oblectamenta assembler.
;;
;; The face `ceps-si-unit-face' marks the fourteen names that silently resolve
;; to SI units rather than to whatever you meant -- see DEFECTS.md D17.  That
;; defect produces a wrong answer with exit code 0 and no diagnostic, so the
;; names are given a face of their own and deliberately do not look like names
;; you introduced.

;;; Code:

(defgroup ceps nil
  "Major mode for the ceps language."
  :group 'languages
  :prefix "ceps-")

(defface ceps-si-unit-face
  '((t :inherit font-lock-warning-face))
  "Face for names that silently resolve to an SI unit (DEFECTS.md D17).
A variable named `m' binds to metre, not to anything you declared."
  :group 'ceps)

(defconst ceps-control-keywords
  '("else" "for" "if" "return" "static_for")
  "Keywords the ceps lexer turns into a control token.")

(defconst ceps-declaration-keywords
  '("fun" "kind" "label" "let" "macro" "raw_map"
    "struct" "template" "val")
  "Keywords the ceps lexer turns into a declaration token.")

(defconst ceps-si-units
  '("ampere" "candela" "cd" "celsius" "kelvin" "kg"
    "kilogram" "m" "meter" "metre" "mol" "mole"
    "s" "second")
  "Names that silently resolve to an SI unit.  See DEFECTS.md D17.")

(defconst ceps-registers
  '("ARG0" "ARG1" "ARG2" "ARG3" "ARG4" "ARG5"
    "FP" "R0" "R1" "R10" "R11" "R12"
    "R13" "R14" "R15" "R2" "R3" "R4"
    "R5" "R6" "R7" "R8" "R9" "RES"
    "SP" "addr" "reg")
  "Oblectamenta registers and operand modifiers.")

(defconst ceps-opcodes
  '("adddbl" "addi32" "addi64" "andi32" "andi64"
    "andni32" "andni64" "assert_deserialized_protobufish_message_equals_str" "assert_empty_cs" "asserteqi32"
    "assertf64" "asserti32" "asserti64" "assertsz" "atandbl"
    "beq" "beqi64" "beqi8" "bgteq" "bgteqzeroi32"
    "blt" "blteq" "blteqzeroi32" "bltzeroi32" "bneqi64"
    "bneqi8" "bnzerodbl" "bnzeroi32" "bnzeroi64" "bnzeroi8"
    "buc" "bzerodbl" "bzeroi32" "bzeroi64" "bzeroi8"
    "call" "cosdbl" "cpysi32" "dbg_deserialize_protobufish_to_json" "dbg_print_cs_and_regs"
    "dbg_print_data" "dbg_print_stack" "dbg_print_topf64" "dbg_print_topi32" "dbg_print_topi64"
    "dbg_println" "dbg_printlni32" "dbg_printsz" "discardtopi32" "discardtopi64"
    "divdbl" "divi32" "divi64" "duptopi128" "duptopi192"
    "duptopi32" "duptopi64" "duptopi8" "eqdbl" "eqi32"
    "eqi64" "expdbl" "gtdbl" "gteqdbl" "gteqi32"
    "gteqi64" "gti32" "gti64" "halt" "lddbl"
    "ldi32" "ldi64" "ldi8" "ldptr" "ldsdbl"
    "ldsi32" "ldsi64" "ldsi8" "lea" "lea_absolute"
    "ltdbl" "lteqdbl" "lteqi32" "lteqi64" "lti32"
    "lti64" "msg" "muldbl" "muli32" "muli64"
    "negdbl" "negi32" "negi64" "noop" "noti32"
    "noti64" "ori32" "ori64" "popi32" "popi64"
    "pushi32" "pushi64" "remi32" "remi64" "ret"
    "setframe" "shli32" "shli64" "shri32" "shri64"
    "sindbl" "sri64" "stdbl" "sti32" "sti64"
    "sti8" "stptr" "stsdbl" "stsi32" "stsi64"
    "stsi8" "subdbl" "subi32" "subi64" "swp"
    "swp128b8" "swp128i64" "swp192i64" "swp72i64" "swp80i64"
    "swp96i64" "swpi160i64" "swpi16i128" "swpi16i64" "swpi192i32"
    "swpi32i64" "swpi64" "swpi64b128" "swpi64b72" "swpi64i192"
    "swpi8i128" "swpi8i64" "tandbl" "tanhdbl" "ui32toui64"
    "ui8toui32" "ui8toui64" "wrsi32" "xori32" "xori64")
  "Oblectamenta opcodes.")

(defconst ceps-sm-vocabulary
  '("Actions" "Events" "Guards" "Simulation" "Start" "Thread"
    "asm" "data" "global" "msg" "oblectamenta" "on_enter"
    "on_exit" "sm" "states" "t" "text" "transition"
    "x64")
  "Structure names the state machine implementation looks for by name.")

(defconst ceps-font-lock-keywords
  `(;; kind X;
    ("\\_<\\(kind\\)\\s-+\\([A-Za-z_][A-Za-z0-9_]*\\)"
     (1 font-lock-keyword-face) (2 font-lock-type-face))

    (,(regexp-opt ceps-control-keywords 'symbols) . font-lock-keyword-face)
    (,(regexp-opt ceps-declaration-keywords 'symbols) . font-lock-keyword-face)

    ;; D17.  Deliberately ahead of every rule that could claim these names,
    ;; including the declaration rule below: a name that is really a unit must
    ;; not be coloured as a name you introduced.
    (,(regexp-opt ceps-si-units 'symbols) . 'ceps-si-unit-face)

    (,(regexp-opt ceps-registers 'symbols) . font-lock-constant-face)
    (,(regexp-opt ceps-opcodes 'symbols) . font-lock-function-name-face)

    ;; sm{ states{ Actions{ t{ ...
    (,(concat "\\_<" (regexp-opt ceps-sm-vocabulary t) "\\_>\\s-*{")
     (1 font-lock-builtin-face))

    ;; Kind a, b, c;  -- the kind, then the names it introduces.
    ("\\_<\\([A-Z][A-Za-z0-9_]*\\)\\(\\s-+[A-Za-z_][A-Za-z0-9_]*\\s-*\\(?:,\\s-*[A-Za-z_][A-Za-z0-9_]*\\s-*\\)*\\);"
     (1 font-lock-type-face)
     ("[A-Za-z_][A-Za-z0-9_]*"
      (progn (goto-char (match-beginning 2)) (match-end 2))
      nil
      (0 font-lock-variable-name-face)))

    ;; Any other name heading a struct.
    ("\\(?:^\\|[^.[:alnum:]_]\\)\\([A-Za-z_][A-Za-z0-9_]*\\)\\s-*{"
     (1 font-lock-function-name-face))

    ("\\_<[0-9]+\\.[0-9]*\\(?:[eE][-+]?[0-9]+\\)?" . font-lock-constant-face)
    ("\\_<[0-9]+\\_>" . font-lock-constant-face))
  "Font lock keywords for `ceps-mode'.")

(defvar ceps-mode-syntax-table
  (let ((table (make-syntax-table)))
    ;; // line comments and /* block */ comments, as in C.
    (modify-syntax-entry ?/ ". 124b" table)
    (modify-syntax-entry ?* ". 23" table)
    (modify-syntax-entry ?\n "> b" table)
    (modify-syntax-entry ?_ "_" table)
    (modify-syntax-entry ?\" "\"" table)
    (modify-syntax-entry ?\\ "\\" table)
    table)
  "Syntax table for `ceps-mode'.")

;;;###autoload
(define-derived-mode ceps-mode prog-mode "ceps"
  "Major mode for editing ceps files."
  :syntax-table ceps-mode-syntax-table
  (setq-local font-lock-defaults '(ceps-font-lock-keywords))
  (setq-local comment-start "// ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "//+\\s-*")
  (setq-local indent-tabs-mode nil))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.ceps\\'" . ceps-mode))

(provide 'ceps-mode)

;;; ceps-mode.el ends here
